sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_2033876ad444_key -iv $encrypted_2033876ad444_iv -in pet-project-261220-350dbeb9468b.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project pet-project-261220
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials multi-container-app
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t kirillyershov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kirillyershov/react-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
