apiVersion: certificates.k8s.io/v1beta1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kirilyershov.site
  dnsNames:
    - kirilyershov.site
    - www.kirilyershov.site
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - kirilyershov.site
          - www.kirilyershov.site